ALTER TABLE receipts ADD COLUMN image_bytes BLOB NOT NULL DEFAULT x'';
ALTER TABLE receipts ADD COLUMN mime TEXT NOT NULL DEFAULT 'image/jpeg';
ALTER TABLE receipts ADD COLUMN byte_size INTEGER NOT NULL DEFAULT 0;
